### PR TITLE
Add a page to assist users to test the parse server

### PR DESCRIPTION
**Pull request by marcusgadbem**
Hi! I was playing around with Parse server and realized that we could make couple requests from the frontend to the local Parse server (also the cloud code) in order to ensure things are running properly.

This PR contains the page and buttons that helps making those tests easier.
Hope it helps! :)

### CODE REVIEW

**Comment by hramos** [comment]
This is something we've thought about exploring. Several guides do mention that people should look for the "I dream of being a web site" message, so I wouldn't replace the default landing page just yet to avoid any confusion. Can you host this under a different route?

Also, in future PRs that add to the static site it would be useful to include a screenshot of the generated page in the PR description, for review purposes.

**Comment by marcusgadbem** [comment]
Nice. I'm changed root route back to the message and moved test screen to a route named `/test`.
Also made a little fix in CSS `pre` rule to avoid test's output to overflow the box.

Since we are moving the screen to a different route than the root, would be nice to improve [README.md#using-it](https://github.com/ParsePlatform/parse-server-example/blob/master/README.md#using-it) instructions which I also added to this PR if you don't mind.
I still can make any changes if you want me to.

Still for documentation, here are the screenshots of the proposed screen:

parse-ss-1
parse-ss-2
parse-ss-3
parse-ss-4

**Comment by hramos** [comment]
This is great! Thanks a lot.

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [1.2.0](https://github.com/parse-community/parse-server-example/releases/tag/1.2.0)

**Pull request merged**
