### PR TITLE
Updating to Parse-Server 2.1.6

### PR DESCRIPTION
**Pull request by 432player**
Please work!!! :)

### CODE REVIEW

**Comment by peterdotjs** [comment]
Did you mean to open this pull request? You've even added .p12 certs to it.

**Comment by 432player** [comment]
Hi Peter, I think I've made a mistake. I wanted to update to the latest Parse-Server 2.1.6 and I thought that a pull request will do that and apparently I was seriously wrong.
Is there any way I can undo this?
Thanks for letting me know

**Comment by 432player** [comment]
I'll try Close Pull request.
I'm still an infant in the Github arena

**Comment by peterdotjs** [comment]
No worries. You'll definitely want to create some new certs since they're on the web now. To update to 2.1.6 you'll want to change the 'package.json' version and run `npm install again`.

**Comment by 432player** [comment]
Yeah I've eventually figured that out :)
Thanks for your help!
Does anyone have access to the files now that I've closed the pull request?

**Comment by peterdotjs** [comment]
It's still there. I would recommend doing this:

1) Create a new branch (a copy of your master). So all your commits are there.
2) Create a new master branch based off of remote master. And force push to your master. 
3) The PR should update and remove the commits. This way at least at least git history is removed from this point forward.
4) Assume anything you checked in was compromised and change accordingly. 

Hopefully this helps.

**Comment by peterdotjs** [comment]
Actually it doesn't matter to much - you are working on a public fork. So all your files were public anyways.

**Comment by 432player** [comment]
That's true, ok I will see if I can make  a few things private. good thing the app isn't out yet :)

**Comment by thamer898** [comment]
Hello @peterdotjs 

i have successfully update my parse server to be 2.1.6 i need two things from you please :+1: 

1. allow user to reset password .
2. configure Push notifications on server side & client side for android .


Regards

**Pull request closed without merging**
