### PR TITLE
Deploy with tutum (docker)

### PR DESCRIPTION
**Pull request by didierfranc**
I made this new pull with an automated build of **parse-server-example** as you can see it [here](https://hub.docker.com/r/didierfranc/parse-server-auto/). Indeed it's better than a manual build ...

**Dockerfile** is better with explicit environment variables
**Readme** has now a Tutum deployment button linked with his **tutum.yml**
**Package.json** express and parse dependencies are unnecessary there are in already in `"parse-server": "~2.0"`

### CODE REVIEW

**Comment by gfosco** [comment]
Can you rebase and squash this?

**Comment by didierfranc** [comment]
I made this to get it running instantly https://github.com/didierfranc/parse-docker

**Comment by gfosco** [comment]
How do you keep it up to date?

**Comment by didierfranc** [comment]
It's based on the latest npm version of **parse-server** and **parse-dashboard** and the docker image is build on every Github pull.

**Comment by gfosco** [comment]
That's good then :) I guess we can close this.

**Pull request closed without merging**
