### PR TITLE
change to localhost for Heroku one-click deploys

### PR DESCRIPTION
**Pull request by rogerhu**

### CODE REVIEW

**Comment by drew-gross** [comment]
Can we use `localhost` instead? Having internal requests go out to the public internet by default seems a little silly.

**Comment by gfosco** [comment]
Actually, yeah, that makes sense for a heroku deployment.

**Comment by rogerhu** [comment]
Updated

**Comment by drew-gross** [comment]
I think you still need the mount point in the URL

**Comment by rogerhu** [comment]
oops good call fixed

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [1.2.0](https://github.com/parse-community/parse-server-example/releases/tag/1.2.0)

**Pull request merged**
