### PR TITLE
Add OpenShift template

### PR DESCRIPTION
**Pull request by jsvgoncalves**
* The template should be used with the `$ oc new-app` command
  and the `-f` flag to specify the path to the file
* Adds section on the README about OpenShift deployment

### CODE REVIEW

**Comment by luciddreamz** [comment]
@jsvgoncalves Looks good. Tested and working great!

If anyone needs access to OpenShift Online (Next Gen) Developer Preview in order to review/test this PR, register [here](https://www.openshift.com/devpreview/register.html) and @mention me in a comment and I'll grant you immediate access.

**Comment by dinhxuanvu** [comment]
LGTM

**Comment by developercorey** [comment]
Nice!  Let's get this tested and merged.

**Comment by jsvgoncalves** [comment]
@hramos @gfosco can you pleas review?

**Comment by zh-wowtv** [comment]
Any document about this? I followed [this](https://github.com/antt001/parse-server-example) but can't connect to my mongodb:

> warn: Unable to ensure uniqueness for usernames:  MongoError: failed to connect to server [localhost:43016] on first connect
>     at Pool.<anonymous> (/var/lib/openshift/57f3a8d22d5271067700004b/app-root/runtime/repo/node_modules/mongodb-core/lib/topologies/server.js:313:35)
>     at emitOne (events.js:96:13)
>     at Pool.emit (events.js:188:7)
>     at Connection.<anonymous> (/var/lib/openshift/57f3a8d22d5271067700004b/app-root/runtime/repo/node_modules/mongodb-core/lib/connection/pool.js:260:12)
>     at Connection.g (events.js:291:16)
>     at emitTwo (events.js:106:13)
>     at Connection.emit (events.js:191:7)
>     at Socket.<anonymous> (/var/lib/openshift/57f3a8d22d5271067700004b/app-root/runtime/repo/node_modules/mongodb-core/lib/connection/connection.js:162:49)
>     at Socket.g (events.js:291:16)
>     at emitOne (events.js:96:13)
> warn: Unable to ensure uniqueness for user email addresses:  MongoError: failed to connect to server [localhost:43016] on first connect
>     at Pool.<anonymous> (/var/lib/openshift/57f3a8d22d5271067700004b/app-root/runtime/repo/node_modules/mongodb-core/lib/topologies/server.js:313:35)
>     at emitOne (events.js:96:13)
>     at Pool.emit (events.js:188:7)
>     at Connection.<anonymous> (/var/lib/openshift/57f3a8d22d5271067700004b/app-root/runtime/repo/node_modules/mongodb-core/lib/connection/pool.js:260:12)
>     at Connection.g (events.js:291:16)
>     at emitTwo (events.js:106:13)
>     at Connection.emit (events.js:191:7)
>     at Socket.<anonymous> (/var/lib/openshift/57f3a8d22d5271067700004b/app-root/runtime/repo/node_modules/mongodb-core/lib/connection/connection.js:162:49)
>     at Socket.g (events.js:291:16)
>     at emitOne (events.js:96:13)
> (node:470919) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 4): MongoError: failed to connect to server [localhost:43016] on first connect
> (node:470919) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 5): MongoError: failed to connect to server [localhost:43016] on first connect

It seems the user name and password is not correct. But there is no username and password generated based on the document and I can connect through **rhc port-forward** command.

**Comment by jsvgoncalves** [comment]
@zh-wowtv as stated, this template is for OpenShift Online (Next Gen), not for OpenShift v2.

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [1.2.0](https://github.com/parse-community/parse-server-example/releases/tag/1.2.0)

**Pull request merged**
