### PR TITLE
Example for serving files from parse/public directory like a domain.parseapp.com webapp.

### PR DESCRIPTION
**Pull request by mrsmuneton**

### CODE REVIEW

**Comment by gfosco** [comment]
Sure.. it might even make sense to just make that the default behavior too.  We can revisit that later.  Thanks :+1:

**Comment by mrsmuneton** [comment]
thanks @gfosco! excited to have my commit merged =)

**Comment by marcusgadbem** [comment]
Hi, @mrsmuneton and @gfosco. I just realized this PR is related to one which was merged a few days ago. 
This PR suggests the addition of a express config to serve static assets but it is already set (https://github.com/ParsePlatform/parse-server-example/blob/master/index.js#L28).
I suggest we could just rearranje the comment/line in order to avoid confusing users with duplicated configurations.
I'm available do that if you want me to. :)

**Comment by mrsmuneton** [comment]
@marcusgadbem i see what you mean, that is duplicate now so that sounds like a good idea for you to rearrange like that, thanks for the followup :+1:

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [1.2.0](https://github.com/parse-community/parse-server-example/releases/tag/1.2.0)

**Pull request merged**
